name: Deploy to Google Apps Script on Release

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install clasp
      run: npm install -g @google/clasp

    - name: Create .clasprc.json for authentication
      run: echo '${{ secrets.CLASPRC_JSON }}' > ~/.clasprc.json

    - name: Google Apps Script Login Info
      run: clasp show-authorized-user

    - name: Push files to Apps Script
      # --force 옵션은 원격 appsscript.json 파일을 덮어쓰기 위해 필요합니다.
      run: clasp push --force

    - name: Create new version on tag push
      # 태그가 푸시되었을 때만 이 단계를 실행합니다.
      if: startsWith(github.ref, 'refs/tags/')
      run: clasp create-version "Release ${{ github.ref_name }}"

    - name: Create new deployment
      # 이 명령은 매번 새로운 배포를 생성합니다.
      # 기존 배포를 업데이트하려면, DEPLOYMENT_ID 시크릿을 설정하고 아래 주석 처리된 명령을 사용하세요.
      # run: clasp update-deployment ${{ secrets.DEPLOYMENT_ID }} --description "Release ${{ github.event.release.name }} (${{ github.ref_name }})"
      run: clasp create-deployment --description "Release ${{ github.event.release.name }} (${{ github.ref_name }})"

