name: Deploy to Google Apps Script

on:
  push:
    tags:
      - 'v*'

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install clasp
      run: npm install -g @google/clasp

    - name: Create .clasprc.json for authentication
      run: echo '${{ secrets.CLASPRC_JSON }}' > /home/runner/.clasprc.json

    - name: 0. Google Apps Script Login Info
      run: clasp show-authorized-user --auth /home/runner/.clasprc.json

    - name: 1. Push code to Google Apps Script
      run: clasp push --auth /home/runner/.clasprc.json

    - name: 2. Deploy a new version
      run: clasp deploy --auth /home/runner/.clasprc.json 